<?php
$config['protocol']='smtp';
$config['smtp_host']='ssl://smtp.gmail.com';
$config['smtp_port']='465';
$config['smtp_user']='webbjing@gmail.com';
$config['smtp_pass']='pig910107';
$config['mailtype']='html';
$config['charset']='iso-8859-1';
$config['wordwrap']=TRUE;
$config['newline']="\r\n";
?>